name: publish-with-provenance
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to publish to'
        required: true
        default: 'production'
        type: choice
        options:
        - staging
        - production
      cli_version:
        description: 'npm CLI version to install'
        required: true
        default: 'latest'
        type: string

jobs:
  debug:
    permissions:
      actions: read
      id-token: write
      contents: read
    uses: bdehamer/workflows/.github/workflows/oidc-dump.yml@main
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout source
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3
      - name: Setup node
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # v3
        with:
          node-version: 18
          registry-url: ${{ github.event.inputs.environment == 'production' && 'https://registry.npmjs.com' || secrets.NPM_REGISTRY_STAGING }}
          check-latest: true
      - name: Bump package versions
        run: |
          sed -i "s/1.0.0/1.0.0-${GITHUB_RUN_ID}.${GITHUB_RUN_ATTEMPT}/" "package.json"
      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ github.event.inputs.environment == 'production' && secrets.NPM_TOKEN_PRODUCTION || secrets.NPM_TOKEN_STAGING }}
        run: |
          npm install -g npm@${{ github.event.inputs.cli_version }} --registry https://registry.npmjs.com
          npm install --registry https://registry.npmjs.com
          npm pack --json
          TARBALL=$(readlink -f  *.tgz)
          npm publish ${TARBALL} --provenance --access public
      - uses: actions/upload-artifact@v3
        with:
          name: package.tgz
          path: ./*.tgz
